package com.veygard.android.geoquiz

import androidx.annotation.StringRes

class Question(val text: String, val answer: Boolean, var questionShowed: Boolean) {

    companion object {
        fun getQuestionList(): List<Question> {
            return listOf(
                Question("Ворона и сорока — одно и то же. ", false, true),
                Question("Рубанок — инструмент столяра. ", true, false),
//                Question("Кашпо — вид шарфа. ", false, false),
//                Question("Бобслей — санный вид спорта. ", true, false),
//                Question("23:00 — то же, что 8 часов вечера. ", false, false),
//                Question("Мэри Поппинс родом из Франции. ", false, false),
//                Question("Английский алфавит длиннее русского. ", false, false),
//                Question("В слове «день» 4 звука. ", false, false),
//                Question("Судно с двумя корпусами — катамаран. ", true, false),
//                Question("Октябрь — самый длинный осенний месяц. ", true, false),
//                Question("Столица Египта — Каир. ", true, false),
//                Question("Фортепиано относится к духовым инструментам. ", false, false),
//                Question("Война с Наполеоном была в 1812 году. ", true, false),
//                Question("Изумруд — камень синего цвета. ", false, false),
//                Question("Суши — японское блюдо. ", true, false),
//                Question("Рождество в России отмечают 14 января. ", false, false),
//                Question("Цветик-семицветик исполнял желания. ", true, false),
//                Question("Антрекот — это пирожное. ", false, false),
//                Question("Емеля поймал Золотую рыбку. ", false, false),
//                Question("Если сегодня четверг, то позавчера был вторник. ", true, false),
//                Question("Голкипер — это защитник в хоккее. ", true, false),
//                Question("Семнадцать делится на семь. ", false, false),
//                Question("Помадой красят ресницы. ", false, false),
                Question("Майор — это звание между капитаном и подполковником. ", true, false),
                Question("Голландия — то же самое, что и Нидерланды. ", true, false),
                Question("Дагестан находится в России. ", true, false),
                Question("Чечётка — это название танца. ", true, false),
                Question("В слове «пень» один слог. ", true, false),
                Question("Коалы обитают в Норвегии. ", false, false),
                Question("На футбольном поле двое ворот. ", true, false),
                Question("Динозавров изучает палеонтология. ", true, false),
//                Question("Хомяки являются хищниками. ", false, false),
//                Question("Кондитер изготавливает обувь. ", false, false),
//                Question("У флейты есть струны. ",false, false),
//                Question("Ежи впадают в спячку. ",true, false),
//                Question("Лезгинка — грузинское блюдо. ",false, false),
//                Question("В баскетболе используются мяч. ",true, false),
//                Question("В слове «переезд» есть приставка. ",true, false),
//                Question("Зелёный сигнал светофора означает, что нужно стоять. ",false, false),
//                Question("Эклер — это мясное блюдо. ",false, false),
//                Question("Нарвал живёт в море. ",true, false),
//                Question("Помидор — это корнеплод. ",false, false),
//                Question("Ридикюль — разновидность сумочки. ",true, false),
//                Question("Кипяток загасит огонь быстрее холодной воды. ",true, false),
//                Question("Пирсинг — это вид спорта. ",false, false),
//                Question("Полное имя Димы — Владимир. ",false, false),
//                Question("Вороны питаются только сыром. ",false, false),
//                Question("Про Каштанку написал Чехов. ",true, false),
//                Question("Уфа — это город в России. ",true, false),
//                Question("Слова «день» и «ночь» женского рода. ",false, false),
//                Question("Берлин — столица Лондона. ",false, false),
//                Question("Красная Шапочка шла к дедушке. ",false, false),
//                Question("Курочку Рябу придумал Лев Толстой. ",false, false),
//                Question("Парфюмер занимается духами. ",true, false),
//                Question("Коровы относятся к травоядным. ",true, false),
//                Question("В прятки можно играть только вдвоем. ",false, false),
//                Question("У сына Никиты отчество Николаевич. ",false, false),
//                Question("Отец жены — тесть. ",true, false),
//                Question("Пончики делают из теста. ",true, false),
//                Question("Пекин — столица Китая. ",true, false),
//                Question("Три сантиметра — это больше, чем четыре миллиметра. ",true, false),
//                Question("В 2013 году было 11 месяцев. ",false, false),
//                Question("Лицо рыцаря закрывается забралом. ",true, false),
//                Question("В слове «тень» все согласные мягкие. ",true, false),
//                Question("Трижды пять — пятнадцать. ",true, false),
//                Question("После мая наступает апрель. ",false, false),
//                Question("Леонардо — главный из черепашек-ниндзя. ",true, false),
//                Question("Древней Русью правили фараоны. ",false, false),
//                Question("Милан находится в России. ",false, false),
//                Question("«Добро» и «зло» — антонимы. ",true, false),
//                Question("Пингвины живут в Антарктиде. ",true, false),
//                Question("Криштиану Роналду — футболист. ",true, false),
//                Question("Архитектор — тот, кто проектирует здания. ",true, false),
//                Question("В борщ добавляют свёклу. ",true, false),
//                Question("Кузен — это старший брат. ",false, false),
//                Question("Пиала — это чашка без ручек. ",true, false),
//                Question("Цыплёнок — детёныш курицы. ",true, false),
//                Question("Художественная борьба — олимпийский вид спорта. ",false, false),
//                Question("В английском алфавите нет буквы А. ",false, false),
//                Question("Рапира — это разновидность шпаги. ",true, false),
//                Question("Река Амазонка протекает в Южной Америке. ",true, false),
//                Question("Ж — звонкий согласный. ",true, false),
//                Question("Актиния — это морской обитатель. ",true, false),
//                Question("Синхронная ходьба — командный вид спорта. ",false, false),
//                Question("Пирамиды построили древние греки. ",false, false),
//                Question("При близорукости плохо видно то, что близко. ",false, false),
//                Question("Китай — единственная страна, где растут голубые розы. ",false, false),
//                Question("Семерых козлят съела лиса. ",false, false),
//                Question("Мать мужа — тёща. ",false, false),
//                Question("Дуремар занимался продажей лягушек. ",false, false),
//                Question("Тонометром измеряют давление. ",true, false),
//                Question("В слове «ненастье» пять гласных. ",false, false),
//                Question("Один из Смешариков был бараном. ",true, false),
//                Question("Мыши не охотятся на кошек. ",true, false),
//                Question("Сервал относится к копытным. ",false, false),
//                Question("13 — простое число.  ",true, false),
//                Question("Греция была столицей Рима. ",false, false),
//                Question("Волга — это река в Африке. ",false, false),
//                Question("Кондитер делает сладости.  ",true, false),
                Question("Тетерев — то же, что глухарь. ", false, false)
            )
        }
    }
}